### ISSUE TITLE
[Bug] Syntax error in the install.yml

### ISSUE THREAD

**Issue by LaMonF** [bacardi55/kalliope-picamera#1]
The error appears to have been in '/var/tmp/resources/neurons/camera/install.yml': line 9, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: "Install pip dependencies"
    pip:
    ^ here

**Comment by bacardi55** [comment]
Thanks for the review, sometimes my vim setup play with my yml indentation ^^
should be fixed by this commit https://github.com/bacardi55/kalliope-picamera/commit/9eeac25764e76c7814a4297dd7def2f9a78f1252
